apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo-runners
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  config.yaml: |
    runner:
      capacity: 5
      labels:
        - "ubuntu-latest:docker.io/gitea/runner-images:ubuntu-22.04"
        - "alpine-base:docker.io/catthehacker/container-architecture-alpine:3.19"
    
    container:
      network: ""
      valid_volumes:
        - '**'
      options: "-v /certs/client"
      
      kubernetes:
        namespace: "forgejo-runners"
        pod_template: |
          apiVersion: v1
          kind: Pod
          metadata:
            generateName: forgejo-job-
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              fsGroup: 1000
            containers:
              - name: job
                resources:
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
                  limits:
                    cpu: "2000m"
                    memory: "2Gi"
                volumeMounts:
                  - name: workspace
                    mountPath: /workspace
            volumes:
              - name: workspace
                emptyDir:
                  sizeLimit: 4Gi