apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-logs-single
    targetRevision: 0.12.1
    helm:
      values: |
        fullnameOverride: "victoria-logs"
        server:
          service:
            servicePort: 9428
            name: http
          
          # --- LONGHORN PERSISTENCE ---
          persistentVolume:
            enabled: true
            size: 10Gi
            storageClassName: "longhorn-single-replica"
          retentionPeriod: 7d

          # Resource limits
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true