apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-vlagent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-logs-collector
    targetRevision: 0.3.1 
    helm:
      values: |
        fullnameOverride: "vlagent"
        
        remoteWrite:
          - url: "http://victoria-logs-server.victoria.svc.cluster.local:9428/insert/native"

        # Resource limits
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria
  syncPolicy:
    automated:
      prune: true
      selfHeal: true